/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Animal
 */


public class Animal {
  @SerializedName("id")
  private Long id = null;

  @SerializedName("species")
  private String species = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("age")
  private Integer age = null;

  /**
   * Gets or Sets gender
   */
  @JsonAdapter(GenderEnum.Adapter.class)
  public enum GenderEnum {
    MALE("MALE"),
    FEMALE("FEMALE");

    private String value;

    GenderEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static GenderEnum fromValue(String input) {
      for (GenderEnum b : GenderEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<GenderEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final GenderEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public GenderEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return GenderEnum.fromValue((String)(value));
      }
    }
  }  @SerializedName("gender")
  private GenderEnum gender = null;

  @SerializedName("enclosureId")
  private Long enclosureId = null;

  /**
   * Gets or Sets status
   */
  @JsonAdapter(StatusEnum.Adapter.class)
  public enum StatusEnum {
    ACTIVE("ACTIVE"),
    SOLD("SOLD"),
    DEAD("DEAD");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static StatusEnum fromValue(String input) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<StatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public StatusEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return StatusEnum.fromValue((String)(value));
      }
    }
  }  @SerializedName("status")
  private StatusEnum status = null;

  /**
   * Gets or Sets acquisitionType
   */
  @JsonAdapter(AcquisitionTypeEnum.Adapter.class)
  public enum AcquisitionTypeEnum {
    BOUGHT("BOUGHT"),
    OFFSPRING("OFFSPRING");

    private String value;

    AcquisitionTypeEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static AcquisitionTypeEnum fromValue(String input) {
      for (AcquisitionTypeEnum b : AcquisitionTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<AcquisitionTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final AcquisitionTypeEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public AcquisitionTypeEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return AcquisitionTypeEnum.fromValue((String)(value));
      }
    }
  }  @SerializedName("acquisitionType")
  private AcquisitionTypeEnum acquisitionType = null;

  public Animal id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public Animal species(String species) {
    this.species = species;
    return this;
  }

   /**
   * Get species
   * @return species
  **/
  @Schema(required = true, description = "")
  public String getSpecies() {
    return species;
  }

  public void setSpecies(String species) {
    this.species = species;
  }

  public Animal name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Animal age(Integer age) {
    this.age = age;
    return this;
  }

   /**
   * Get age
   * @return age
  **/
  @Schema(description = "")
  public Integer getAge() {
    return age;
  }

  public void setAge(Integer age) {
    this.age = age;
  }

  public Animal gender(GenderEnum gender) {
    this.gender = gender;
    return this;
  }

   /**
   * Get gender
   * @return gender
  **/
  @Schema(required = true, description = "")
  public GenderEnum getGender() {
    return gender;
  }

  public void setGender(GenderEnum gender) {
    this.gender = gender;
  }

  public Animal enclosureId(Long enclosureId) {
    this.enclosureId = enclosureId;
    return this;
  }

   /**
   * Get enclosureId
   * @return enclosureId
  **/
  @Schema(description = "")
  public Long getEnclosureId() {
    return enclosureId;
  }

  public void setEnclosureId(Long enclosureId) {
    this.enclosureId = enclosureId;
  }

  public Animal status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @Schema(required = true, description = "")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  public Animal acquisitionType(AcquisitionTypeEnum acquisitionType) {
    this.acquisitionType = acquisitionType;
    return this;
  }

   /**
   * Get acquisitionType
   * @return acquisitionType
  **/
  @Schema(required = true, description = "")
  public AcquisitionTypeEnum getAcquisitionType() {
    return acquisitionType;
  }

  public void setAcquisitionType(AcquisitionTypeEnum acquisitionType) {
    this.acquisitionType = acquisitionType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Animal animal = (Animal) o;
    return Objects.equals(this.id, animal.id) &&
        Objects.equals(this.species, animal.species) &&
        Objects.equals(this.name, animal.name) &&
        Objects.equals(this.age, animal.age) &&
        Objects.equals(this.gender, animal.gender) &&
        Objects.equals(this.enclosureId, animal.enclosureId) &&
        Objects.equals(this.status, animal.status) &&
        Objects.equals(this.acquisitionType, animal.acquisitionType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, species, name, age, gender, enclosureId, status, acquisitionType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Animal {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    species: ").append(toIndentedString(species)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    age: ").append(toIndentedString(age)).append("\n");
    sb.append("    gender: ").append(toIndentedString(gender)).append("\n");
    sb.append("    enclosureId: ").append(toIndentedString(enclosureId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    acquisitionType: ").append(toIndentedString(acquisitionType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
