/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.Animal;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for AnimalControllerApi
 */
@Ignore
public class AnimalControllerApiTest {

    private final AnimalControllerApi api = new AnimalControllerApi();

    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteAnimalTest() throws Exception {
        Long id = null;
        api.deleteAnimal(id);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getAnimalTest() throws Exception {
        Long id = null;
        Animal response = api.getAnimal(id);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getAnimalsTest() throws Exception {
        List<Animal> response = api.getAnimals();

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getAnimals1Test() throws Exception {
        Long enclosureId = null;
        List<Animal> response = api.getAnimals1(enclosureId);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void insertAnimalTest() throws Exception {
        Animal body = null;
        Animal response = api.insertAnimal(body);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateAnimalTest() throws Exception {
        Animal body = null;
        Animal response = api.updateAnimal(body);

        // TODO: test validations
    }
}
