/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.SalesBooth;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for SalesBoothControllerApi
 */
@Ignore
public class SalesBoothControllerApiTest {

    private final SalesBoothControllerApi api = new SalesBoothControllerApi();

    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteSalesBoothTest() throws Exception {
        Long id = null;
        api.deleteSalesBooth(id);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getSalesBoothsTest() throws Exception {
        List<SalesBooth> response = api.getSalesBooths();

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void insertSalesBoothTest() throws Exception {
        SalesBooth body = null;
        SalesBooth response = api.insertSalesBooth(body);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateSalesBoothTest() throws Exception {
        SalesBooth body = null;
        SalesBooth response = api.updateSalesBooth(body);

        // TODO: test validations
    }
}
